# -*- coding: utf-8 -*-
"""Lista de compras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ck6xV_nryqVs0yUh4CiSBDPznX7gvf_I
"""

itens = []

def main():
    print("Bem-vindo ao Sistema de Gerenciamento de Lista de Compras.")
    while True:
        print("\nMenu:")
        print("1. Adicionar item")
        print("2. Listar todos os itens")
        print("3. Listar apenas pendentes")
        print("4. Marcar item como comprado")
        print("5. Editar quantidade")
        print("6. Remover Item")
        print("7. Sair")

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            nome = input("Informe o item: ").strip()
            if not nome:
                print("Erro: O nome do item não pode ser vazio.")
                continue

            try:
                qtd = int(input(f"Informe a quantidade de '{nome}': "))
                if qtd <= 0:
                    print("Erro: A quantidade deve ser maior que zero.")
                    continue
                adicionar_item(nome, qtd)
            except ValueError:
                print("Erro: Quantidade deve ser um número inteiro.")

        elif escolha == '2':
            listar_item(apenas_pendentes=False)

        elif escolha == '3':
            listar_item(apenas_pendentes=True)

        elif escolha == '4':
            listar_item()
            if itens:
                try:
                    indice = int(input("Número do item comprado: ")) - 1
                    marcar_comprado(indice)
                except ValueError:
                    print("Entrada inválida! Digite um número.")

        elif escolha == '5':
            listar_item(apenas_pendentes=False)
            if itens:
                try:
                  indice = int(input("Número do item para editar quantidade: ")) -1
                  editar_quantidade(indice)
                except ValueError:
                  print("Entrada inválida! Digite um número")

        elif escolha == '6':
            listar_item()
            if itens:
                try:
                    indice = int(input("Número do item para remover: ")) - 1
                    remover_item(indice)
                except ValueError:
                    print("Entrada inválida! Digite um número.")

        elif escolha == '7':
            print("Saindo do Sistema! Até breve!")
            break
        else:
            print("Opção Inválida!")

def adicionar_item(descricao, quantidade):
    itens.append({"nome": descricao, "quantidade": quantidade, "comprado": False})
    print(f"Item '{descricao}' adicionado com sucesso!")

def listar_item(apenas_pendentes=False):
    lista_exibicao = [i for i in itens if not i["comprado"]] if apenas_pendentes else itens

    if not lista_exibicao:
        print("\nNenhum item encontrado!")
        return

    titulo = "ITENS PENDENTES" if apenas_pendentes else "LISTA DE COMPRAS"
    print(f"\n--- {titulo} ---")
    for i, item in enumerate(itens):
        if apenas_pendentes and item["comprado"]:
            continue
        status = '[X]' if item["comprado"] else "[ ]"
        print(f"{i+1}. {status} {item['nome']} - Qtd: {item['quantidade']}")

def marcar_comprado(indice):
    if 0 <= indice < len(itens):
        itens[indice]["comprado"] = True
        print(f"Item '{itens[indice]['nome']}' marcado como comprado!")
    else:
        print("Erro: Item não encontrado.")

def editar_quantidade(indice):
    if 0 <= indice < len(itens):
        try:
            nova_qtd = int(input(f"Informe a nova quantidade para '{itens[indice]['nome']}': "))
            if nova_qtd > 0:
                itens[indice]["quantidade"] = nova_qtd
                print("Quantidade atualizada com sucesso!")
            else:
                print("Erro: A quantidade deve ser maior que zero.")
        except ValueError:
            print("Erro: Digite um número inteiro.")
    else:
        print("Erro: Item não encontrado.")

def remover_item(indice):
    if 0 <= indice < len(itens):
        removido = itens.pop(indice)
        print(f"Item '{removido['nome']}' removido com sucesso!")
    else:
        print("Erro: Item não encontrado.")

if __name__ == "__main__":
    main()